### ISSUE TITLE
Use of undeclared type 'OrdinaryCoding'

### ISSUE THREAD

**Issue by navanchauhan** [artrmz/ReadTimePublishPlugin#1]
I have installed the dependencies and imported the plugin

```
...
private extension Node where Context == HTML.BodyContext {
    static func wrapper(_ nodes: Node...) -> Node {
        .div(.class("wrapper"), .group(nodes))
    }
    static func contentHeader(for item: Item<OrdinaryCoding>, home: Bool = true) -> Node {
        .unwrap(item.readTime().time, { .span(.class("readTime"), "\($0) min\(home ? "" : " read")") })
    }
...
``` 

But it is giving the error, use of undeclared type 'OrdinaryCoding'

Could you attach your Theme.Swift?

**Comment by artur-ios-dev** [comment]
Well, it's just an example taken from my project. 

`.unwrap(item.readTime().time, { .span("\($0) min") })`

This is one really matters for you. I will improve the README to make it more clear.

This plugin is just an extension to the Publish's Item class, so you can get a time (in minutes) like this:
`item.readTime().time`
this `readTime` method can also accept some parameters (ie. you can change avg words per minute, or you can set it yo return time in seconds instead of minutes).

**Comment by navanchauhan** [comment]
Thank you for such a quick response, closing because this solved my issue
